name: app64cards
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  share: ^0.6.3+5
  url_launcher: ^5.4.1
  path_provider: ^1.6.1
#  fluro: ^1.5.2

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/bm_cards-134.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  assets:
    - images/
    - text/
    - images/mini/
  uses-material-design: true